# Generated by Django 5.0.1 on 2025-12-01 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the workflow is active')),
                ('webhook_token', models.CharField(blank=True, help_text='Unique token for webhook URL', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('gemini', 'Gemini AI'), ('groq', 'Groq AI'), ('google_sheets_read', 'Google Sheets - Read'), ('google_sheets_write', 'Google Sheets - Write'), ('google_docs_create', 'Google Docs - Create'), ('google_docs_append', 'Google Docs - Append'), ('google_drive_upload', 'Google Drive - Upload'), ('google_drive_list', 'Google Drive - List'), ('google_photos_upload', 'Google Photos - Upload'), ('google_photos_list', 'Google Photos - List'), ('whatsapp_send', 'WhatsApp - Send Message'), ('webhook_trigger', 'Webhook Trigger'), ('data_transform', 'Data Transform')], max_length=50)),
                ('name', models.CharField(help_text='Custom name for this node', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Execution order in the workflow')),
                ('config', models.JSONField(default=dict, help_text='Node configuration as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_data', models.JSONField(blank=True, help_text='Input data that triggered the workflow', null=True)),
                ('output_data', models.JSONField(blank=True, help_text='Final output of the workflow', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed')),
                ('node_results', models.JSONField(default=list, help_text='Results from each node execution')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Execution Log',
                'verbose_name_plural': 'Execution Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
